//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.PolicyService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        public int PolicyNumber { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
    
        public virtual PrimaryInsured PrimaryInsured { get; set; }
        public virtual RiskInsured RiskInsured { get; set; }
    }
}
