//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.PolicyService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrimaryInsured
    {
        public int PolicyNumber { get; set; }
        public int AddressId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Policy Policy { get; set; }
    }
}
